### ISSUE TITLE
Task-1 Website horizontal scroll  

### ISSUE THREAD

**Issue by helios1101** [helios1101/HacktoberFest_19#103]
Try to remove horizontal scrolling from website https://helios1101.github.io/HacktoberFest_19/Task1/
made in [Task-1](https://github.com/helios1101/HacktoberFest_19/tree/master/Task1)

**Comment by poonam125sharma** [comment]
I want to try this issue

**Comment by poonam125sharma** [comment]
Please find the #107 fix

**Comment by lordkerwin** [comment]
can I have a go at this?

**Comment by helios1101** [comment]
@poonam125sharma your pull request had a lot of merge conflicts, try to submit with a cleaner code.

**Comment by helios1101** [comment]
@lordkerwin you too can try and reference this issue.

**Comment by greyhatlinux** [comment]
any progress ?
@poonam125sharma 
@lordkerwin

**Comment by greyhatlinux** [comment]
horizontal scrolling fixed!
refer [this](https://github.com/helios1101/HacktoberFest_19/commit/e2dad8664a99b1a5f596b8b2ee90ac15595a73bc#diff-7140ca951838dba84d96f044eed8b03b).
