### ISSUE TITLE
Formatting the index.html file of Task-1

### ISSUE THREAD

**Issue by helios1101** [helios1101/HacktoberFest_19#118]
[Task-1](https://github.com/helios1101/HacktoberFest_19/tree/master/Task1) has an index.html with needs to be properly formatted using the prettier extension in VS code or similar.

**Comment by boreme12** [comment]
Hi, can I have this?

**Comment by helios1101** [comment]
Sure @boreme12 waiting for your pull request!

**Comment by helios1101** [comment]
Great Work @boreme12! Keep contributing :smiley:
