### ISSUE TITLE
Hacktoberfest says this is an invalid repository that doesn't align with it's core values.

### ISSUE THREAD

**Issue by 9112Michael** [helios1101/HacktoberFest_19#195]

**Comment by greyhatlinux** [comment]
We initiated the repo trying to reach out to the beginners. We wanted them to teach them the basics of Git and GitHub through these interactive tasks. Our focus was on the first-timers to the open-source projects.
But HacktoberFest sees it as an attempt to distribute free Tshirts to all, and consequently has declared it invalid.

**Comment by 9112Michael** [comment]
Thanks for your efforts to help beginners learn the basics, I enjoyed the experience.
